behaviors:
  RubyBasic:
    trainer_type: ppo

    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4

    network_settings:
      normalize: false
      hidden_units: 128
      num_layers: 2

    max_steps: 5.0e5
    summary_freq: 10000
    checkpoint_interval: 50000

    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
